<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS><TS version="2.1" language="es_ES">
<context>
    <name>GeoPackageConverterPlugin</name>
    <message><source>Apri GeoPackage Converter</source><translation>Abrir GeoPackage Converter</translation></message>
    <message><source>Converti file vettoriali in GeoPackage</source><translation>Convertir archivos vectoriales a GeoPackage</translation></message>
</context>
<context>
    <name>GeoPackageConverterDialog</name>
    <!-- retranslate_ui strings -->
    <message><source>GeoPackage Converter</source><translation>GeoPackage Converter</translation></message>
    <message><source>Da progetto</source><translation>Desde proyecto</translation></message>
    <message><source>Da cartella</source><translation>Desde carpeta</translation></message>
    <message><source>Seleziona i layer vettoriali del progetto da convertire in GeoPackage.</source><translation>Selecciona las capas vectoriales del proyecto a convertir en GeoPackage.</translation></message>
    <message><source>Seleziona tutto</source><translation>Seleccionar todo</translation></message>
    <message><source>Deseleziona tutto</source><translation>Deseleccionar todo</translation></message>
    <message><source>Cartella di input:</source><translation>Carpeta de entrada:</translation></message>
    <message><source>Sfoglia…</source><translation>Examinar…</translation></message>
    <message><source>Replica struttura su disco</source><translation>Replicar estructura en disco</translation></message>
    <message><source>Scansiona cartella</source><translation>Escanear carpeta</translation></message>
    <message><source>Nome</source><translation>Nombre</translation></message>
    <message><source>Formato</source><translation>Formato</translation></message>
    <message><source>Geometria</source><translation>Geometría</translation></message>
    <message><source>CRS</source><translation>CRS</translation></message>
    <message><source>N° feature</source><translation>N° features</translation></message>
    <message><source>Encoding</source><translation>Codificación</translation></message>
    <message><source>Avvisi</source><translation>Avisos</translation></message>
    <message><source>Opzioni di conversione</source><translation>Opciones de conversión</translation></message>
    <message><source>CRS di destinazione:</source><translation>CRS de destino:</translation></message>
    <message><source>Strategia di raggruppamento:</source><translation>Estrategia de agrupación:</translation></message>
    <message><source>Salva stili</source><translation>Guardar estilos</translation></message>
    <message><source>Valida geometrie</source><translation>Validar geometrías</translation></message>
    <message><source>Dry-run (anteprima)</source><translation>Dry-run (vista previa)</translation></message>
    <message><source>Apri cartella</source><translation>Abrir carpeta</translation></message>
    <message><source>Apri report</source><translation>Abrir reporte</translation></message>
    <message><source>Esegui</source><translation>Ejecutar</translation></message>
    <message><source>Annulla</source><translation>Cancelar</translation></message>
    <message><source>Chiudi</source><translation>Cerrar</translation></message>
    <!-- functional strings -->
    <message><source>(nessuna riproiezione)</source><translation>(sin reproyección)</translation></message>
    <message><source>(nessun layer vettoriale nel progetto)</source><translation>(no hay capas vectoriales en el proyecto)</translation></message>
    <message><source>Seleziona cartella</source><translation>Seleccionar carpeta</translation></message>
    <message><source>Seleziona GeoPackage di output</source><translation>Seleccionar GeoPackage de salida</translation></message>
    <message><source>Seleziona cartella di output</source><translation>Seleccionar carpeta de salida</translation></message>
    <message><source>Cartella non valida</source><translation>Carpeta no válida</translation></message>
    <message><source>Seleziona una cartella esistente.</source><translation>Selecciona una carpeta existente.</translation></message>
    <message><source>Scansione in corso: {f}</source><translation>Escaneando: {f}</translation></message>
    <message><source>Trovati {n} file supportati</source><translation>Encontrados {n} archivos compatibles</translation></message>
    <message><source>Nessun file vettoriale trovato.</source><translation>No se encontraron archivos vectoriales.</translation></message>
    <message><source>Cartella vuota</source><translation>Carpeta vacía</translation></message>
    <message><source>La cartella selezionata non contiene file vettoriali supportati.
&#xa;Formati supportati: SHP, TAB, KML, KMZ, GML, GeoJSON, DXF, GPX, MIF, ZIP.</source><translation>La carpeta seleccionada no contiene archivos vectoriales compatibles.
&#xa;Formatos compatibles: SHP, TAB, KML, KMZ, GML, GeoJSON, DXF, GPX, MIF, ZIP.</translation></message>
    <message><source>Scansione interrotta o fallita.</source><translation>Escaneo cancelado o fallido.</translation></message>
    <message><source>Nessun elemento</source><translation>Sin elementos</translation></message>
    <message><source>La cartella non contiene file vettoriali supportati.</source><translation>La carpeta no contiene archivos vectoriales compatibles.</translation></message>
    <message><source>Seleziona almeno un layer.</source><translation>Selecciona al menos una capa.</translation></message>
    <message><source>Errore output</source><translation>Error de salida</translation></message>
    <message><source>Impossibile creare la cartella: {e}</source><translation>No se pudo crear la carpeta: {e}</translation></message>
    <message><source>Avvio conversione…</source><translation>Iniciando conversión…</translation></message>
    <message><source>Annullamento richiesto…</source><translation>Cancelación solicitada…</translation></message>
    <message><source>Completato: {ok} riusciti, {ko} errori, {w} avvisi</source><translation>Completado: {ok} con éxito, {ko} errores, {w} avisos</translation></message>
    <message><source>Conversione completata: {ok} layer in {nf} file</source><translation>Conversión completada: {ok} capas en {nf} archivos</translation></message>
    <message><source>Conversione fallita: {ko} errori</source><translation>Conversión fallida: {ko} errores</translation></message>
    <message><source>Conversione parziale: {ok} riusciti, {ko} errori</source><translation>Conversión parcial: {ok} con éxito, {ko} errores</translation></message>
    <message><source>Conversione interrotta o fallita.</source><translation>Conversión cancelada o fallida.</translation></message>
    <message><source>GeoPackage di output:</source><translation>GeoPackage de salida:</translation></message>
    <message><source>Cartella di output:</source><translation>Carpeta de salida:</translation></message>
    <message><source>percorso/al/file.gpkg</source><translation>ruta/al/archivo.gpkg</translation></message>
    <message><source>cartella dove generare i .gpkg multipli</source><translation>carpeta donde se generarán los .gpkg múltiples</translation></message>
    <message><source>Caricare i layer nel progetto?</source><translation>¿Cargar las capas en el proyecto?</translation></message>
    <message><source>La conversione ha prodotto {n_files} file GeoPackage con un totale di {n_layers} layer.
&#xa;Vuoi caricare i layer nel progetto QGIS attivo?</source><translation>La conversión ha producido {n_files} archivos GeoPackage con un total de {n_layers} capas.
&#xa;¿Deseas cargar las capas en el proyecto QGIS activo?</translation></message>
    <message><source>Layer aggiunti al progetto: {added}, falliti: {failed}</source><translation>Capas añadidas al proyecto: {added}, fallidas: {failed}</translation></message>
    <!-- short tooltip/status strings -->
    <message><source>CRS di destinazione (clicca per scegliere)</source><translation>CRS de destino (clic para elegir)</translation></message>
    <message><source>Quanti GeoPackage generare e come dividere i layer</source><translation>Cuántos GeoPackage generar y cómo dividir las capas</translation></message>
    <message><source>Percorso del file o cartella di destinazione (modificabile)</source><translation>Ruta del archivo o carpeta de destino (editable)</translation></message>
    <message><source>Apri il selettore di file/cartella</source><translation>Abrir el selector de archivo/carpeta</translation></message>
    <message><source>Salva lo stile di ogni layer dentro il GeoPackage</source><translation>Guardar el estilo de cada capa dentro del GeoPackage</translation></message>
    <message><source>Corregge geometrie invalide prima della scrittura (più lento)</source><translation>Corrige geometrías inválidas antes de la escritura (más lento)</translation></message>
    <message><source>Anteprima: nessuna scrittura su disco</source><translation>Vista previa: sin escritura en disco</translation></message>
    <message><source>Ricrea la struttura cartelle dell'input nell'output</source><translation>Recrea la estructura de carpetas de la entrada en la salida</translation></message>
    <message><source>Sfoglia per selezionare una cartella</source><translation>Examinar para seleccionar una carpeta</translation></message>
    <message><source>Risultato della scansione</source><translation>Resultado del escaneo</translation></message>
    <message><source>Spunta i layer del progetto da convertire</source><translation>Marca las capas del proyecto a convertir</translation></message>
    <message><source>Spunta tutti i layer della lista</source><translation>Marcar todas las capas de la lista</translation></message>
    <message><source>Toglie la spunta a tutti i layer</source><translation>Desmarcar todas las capas</translation></message>
    <message><source>Avvia la conversione</source><translation>Iniciar la conversión</translation></message>
    <message><source>Interrompe la conversione in corso</source><translation>Interrumpir la conversión en curso</translation></message>
    <message><source>Chiude il dialog (le opzioni vengono salvate)</source><translation>Cerrar el diálogo (las opciones se guardan)</translation></message>
    <message><source>Apre la cartella dei file generati</source><translation>Abrir la carpeta de los archivos generados</translation></message>
    <message><source>Riapre il report HTML dell'ultima conversione</source><translation>Reabrir el reporte HTML de la última conversión</translation></message>
    <message><source>Mostra spiegazione dettagliata</source><translation>Mostrar explicación detallada</translation></message>
    <message><source>Opzioni applicate sia alla modalità &lt;i&gt;Da progetto&lt;/i&gt; sia &lt;i&gt;Da cartella&lt;/i&gt;.</source><translation>Opciones aplicadas tanto al modo &lt;i&gt;Desde proyecto&lt;/i&gt; como &lt;i&gt;Desde carpeta&lt;/i&gt;.</translation></message>
    <!-- grouping labels -->
    <message><source>Tutto in un unico GeoPackage</source><translation>Todo en un único GeoPackage</translation></message>
    <message><source>Un GeoPackage per sottocartella</source><translation>Un GeoPackage por subcarpeta</translation></message>
    <message><source>Un GeoPackage per gruppo della legenda</source><translation>Un GeoPackage por grupo de la leyenda</translation></message>
    <!-- long HTML tooltips -->
    <message><source>&lt;b&gt;CRS di destinazione&lt;/b&gt;&lt;br&gt;Riproietta &lt;i&gt;tutte&lt;/i&gt; i layer al sistema di coordinate scelto.&lt;br&gt;&lt;br&gt;Clicca per scegliere &lt;b&gt;qualsiasi&lt;/b&gt; CRS supportato da QGIS, oppure usa il bottone laterale per accedere ai CRS recenti, ai preferiti e alla ricerca completa.&lt;br&gt;&lt;br&gt;&lt;b&gt;Più usati in Italia:&lt;/b&gt;&lt;br&gt;• &lt;b&gt;EPSG:25832 / 25833&lt;/b&gt; — ETRS89 / UTM 32N-33N (standard europeo INSPIRE)&lt;br&gt;• &lt;b&gt;EPSG:32632 / 32633&lt;/b&gt; — WGS 84 / UTM 32N-33N&lt;br&gt;• &lt;b&gt;EPSG:6875 / 6876&lt;/b&gt; — RDN2008 (sistema nazionale corrente)&lt;br&gt;• &lt;b&gt;EPSG:3003 / 3004&lt;/b&gt; — Gauss-Boaga (sistema storico)&lt;br&gt;• &lt;b&gt;EPSG:4326&lt;/b&gt; — WGS 84 geografiche&lt;br&gt;&lt;br&gt;Lascia &lt;i&gt;(nessuna riproiezione)&lt;/i&gt; per mantenere il CRS originale di ogni layer.</source><translation>&lt;b&gt;CRS de destino&lt;/b&gt;&lt;br&gt;Reproyecta &lt;i&gt;todas&lt;/i&gt; las capas al sistema de coordenadas elegido.&lt;br&gt;&lt;br&gt;Haz clic para elegir &lt;b&gt;cualquier&lt;/b&gt; CRS soportado por QGIS, o usa el botón lateral para acceder a los CRS recientes, favoritos y búsqueda completa.&lt;br&gt;&lt;br&gt;&lt;b&gt;Más usados:&lt;/b&gt;&lt;br&gt;• &lt;b&gt;EPSG:25832 / 25833&lt;/b&gt; — ETRS89 / UTM 32N-33N (estándar europeo INSPIRE)&lt;br&gt;• &lt;b&gt;EPSG:32632 / 32633&lt;/b&gt; — WGS 84 / UTM 32N-33N&lt;br&gt;• &lt;b&gt;EPSG:6875 / 6876&lt;/b&gt; — RDN2008 (sistema nacional actual)&lt;br&gt;• &lt;b&gt;EPSG:3003 / 3004&lt;/b&gt; — Gauss-Boaga (sistema histórico)&lt;br&gt;• &lt;b&gt;EPSG:4326&lt;/b&gt; — WGS 84 geográficas&lt;br&gt;&lt;br&gt;Deja &lt;i&gt;(sin reproyección)&lt;/i&gt; para mantener el CRS original de cada capa.</translation></message>
    <message><source>&lt;b&gt;Strategia di raggruppamento&lt;/b&gt;&lt;br&gt;Decide &lt;i&gt;quanti&lt;/i&gt; file GeoPackage verranno generati e come saranno divise i layer:&lt;br&gt;&lt;br&gt;• &lt;b&gt;Tutto in un unico GeoPackage&lt;/b&gt;&lt;br&gt;&#xa0;&#xa0;Un solo file &lt;code&gt;.gpkg&lt;/code&gt; con tutti i layer dentro.&lt;br&gt;• &lt;b&gt;Un GeoPackage per CRS&lt;/b&gt;&lt;br&gt;&#xa0;&#xa0;I layer vengono divise per sistema di coordinate. Utile se hai dati misti.&lt;br&gt;• &lt;b&gt;Un GeoPackage per sottocartella&lt;/b&gt;&lt;br&gt;&#xa0;&#xa0;&lt;i&gt;(solo modalità Da cartella)&lt;/i&gt;. Replica la struttura della cartella di origine.&lt;br&gt;• &lt;b&gt;Un GeoPackage per gruppo della legenda&lt;/b&gt;&lt;br&gt;&#xa0;&#xa0;&lt;i&gt;(solo modalità Da progetto)&lt;/i&gt;. Usa i gruppi del Pannello Layer come criterio.</source><translation>&lt;b&gt;Estrategia de agrupación&lt;/b&gt;&lt;br&gt;Decide &lt;i&gt;cuántos&lt;/i&gt; archivos GeoPackage se generarán y cómo se dividirán las capas:&lt;br&gt;&lt;br&gt;• &lt;b&gt;Todo en un único GeoPackage&lt;/b&gt;&lt;br&gt;&#xa0;&#xa0;Un solo archivo &lt;code&gt;.gpkg&lt;/code&gt; con todas las capas dentro.&lt;br&gt;• &lt;b&gt;Un GeoPackage por CRS&lt;/b&gt;&lt;br&gt;&#xa0;&#xa0;Las capas se dividen por sistema de coordenadas. Útil si tienes datos mixtos.&lt;br&gt;• &lt;b&gt;Un GeoPackage por subcarpeta&lt;/b&gt;&lt;br&gt;&#xa0;&#xa0;&lt;i&gt;(solo modo Desde carpeta)&lt;/i&gt;. Replica la estructura de la carpeta de origen.&lt;br&gt;• &lt;b&gt;Un GeoPackage por grupo de la leyenda&lt;/b&gt;&lt;br&gt;&#xa0;&#xa0;&lt;i&gt;(solo modo Desde proyecto)&lt;/i&gt;. Usa los grupos del Panel de Capas como criterio.</translation></message>
    <message><source>&lt;b&gt;Output&lt;/b&gt;&lt;br&gt;Se la strategia è &lt;i&gt;Tutto in uno&lt;/i&gt;, indica il percorso del file &lt;code&gt;.gpkg&lt;/code&gt;. Il plugin propone un nome di default basato sulla cartella o sul progetto, ma puoi &lt;b&gt;modificarlo liberamente&lt;/b&gt; scrivendo nel campo o usando &lt;i&gt;Sfoglia…&lt;/i&gt;.&lt;br&gt;Per le altre strategie, indica la &lt;b&gt;cartella&lt;/b&gt; dove verranno generati i file (con nomi automatici).</source><translation>&lt;b&gt;Salida&lt;/b&gt;&lt;br&gt;Si la estrategia es &lt;i&gt;Todo en uno&lt;/i&gt;, indica la ruta del archivo &lt;code&gt;.gpkg&lt;/code&gt;. El plugin propone un nombre predeterminado basado en la carpeta o el proyecto, pero puedes &lt;b&gt;modificarlo libremente&lt;/b&gt; escribiendo en el campo o usando &lt;i&gt;Examinar…&lt;/i&gt;.&lt;br&gt;Para las otras estrategias, indica la &lt;b&gt;carpeta&lt;/b&gt; donde se generarán los archivos (con nombres automáticos).</translation></message>
    <message><source>&lt;b&gt;Salva stili&lt;/b&gt;&lt;br&gt;Memorizza lo stile QML di ogni layer dentro il GeoPackage stesso (tabella &lt;code&gt;layer_styles&lt;/code&gt;).&lt;br&gt;&lt;br&gt;Quando riaprirai il &lt;code&gt;.gpkg&lt;/code&gt; in QGIS, lo stile sarà &lt;i&gt;già applicato&lt;/i&gt; senza dover importare manualmente un file &lt;code&gt;.qml&lt;/code&gt;.</source><translation>&lt;b&gt;Guardar estilos&lt;/b&gt;&lt;br&gt;Almacena el estilo QML de cada capa dentro del GeoPackage mismo (tabla &lt;code&gt;layer_styles&lt;/code&gt;).&lt;br&gt;&lt;br&gt;Cuando reabras el &lt;code&gt;.gpkg&lt;/code&gt; en QGIS, el estilo estará &lt;i&gt;ya aplicado&lt;/i&gt; sin necesidad de importar manualmente un archivo &lt;code&gt;.qml&lt;/code&gt;.</translation></message>
    <message><source>&lt;b&gt;Valida geometrie&lt;/b&gt;&lt;br&gt;Esegue l'algoritmo &lt;code&gt;native:fixgeometries&lt;/code&gt; di QGIS su ogni layer &lt;i&gt;prima&lt;/i&gt; della scrittura.&lt;br&gt;&lt;br&gt;Corregge problemi tipici come: anelli che si auto-intersecano, geometrie duplicate, vertici troppo vicini.&lt;br&gt;&lt;br&gt;&lt;b&gt;Attenzione&lt;/b&gt;: rallenta la conversione (anche di molto su dataset grandi). Attiva solo se sai di avere dati 'sporchi'.</source><translation>&lt;b&gt;Validar geometrías&lt;/b&gt;&lt;br&gt;Ejecuta el algoritmo &lt;code&gt;native:fixgeometries&lt;/code&gt; de QGIS en cada capa &lt;i&gt;antes&lt;/i&gt; de la escritura.&lt;br&gt;&lt;br&gt;Corrige problemas típicos como: anillos que se auto-intersecan, geometrías duplicadas, vértices demasiado cercanos.&lt;br&gt;&lt;br&gt;&lt;b&gt;Atención&lt;/b&gt;: ralentiza la conversión (incluso mucho en datasets grandes). Activa solo si sabes que tienes datos 'sucios'.</translation></message>
    <message><source>&lt;b&gt;Dry-run (anteprima)&lt;/b&gt;&lt;br&gt;Modalità simulazione: nessun file viene scritto su disco.&lt;br&gt;&lt;br&gt;Il plugin esegue tutti i controlli (sorgenti, conflitti di nome, raggruppamenti) e produce comunque il &lt;i&gt;report HTML&lt;/i&gt; con quello che &lt;i&gt;sarebbe&lt;/i&gt; stato fatto.&lt;br&gt;&lt;br&gt;Utile per verificare la configurazione prima di una conversione massiva.</source><translation>&lt;b&gt;Dry-run (vista previa)&lt;/b&gt;&lt;br&gt;Modo simulación: no se escribe ningún archivo en disco.&lt;br&gt;&lt;br&gt;El plugin ejecuta todos los controles (fuentes, conflictos de nombre, agrupaciones) y genera igualmente el &lt;i&gt;reporte HTML&lt;/i&gt; con lo que &lt;i&gt;se habría&lt;/i&gt; hecho.&lt;br&gt;&lt;br&gt;Útil para verificar la configuración antes de una conversión masiva.</translation></message>
    <message><source>&lt;b&gt;Replica struttura su disco&lt;/b&gt;&lt;br&gt;&lt;br&gt;Se la tua cartella di input ha sottocartelle annidate, questa opzione decide come vengono organizzati i GeoPackage in uscita.&lt;br&gt;&lt;br&gt;&lt;b&gt;Esempio — la tua cartella:&lt;/b&gt;&lt;br&gt;&lt;pre style=&apos;font-size:11px&apos;&gt;progetto/\n├── strade/\n│   ├── comunali/  →  vie.shp\n│   └── provinciali/  →  strade_sp.shp\n└── edifici/  →  residenziali.shp&lt;/pre&gt;&lt;b&gt;✗ Disattivata&lt;/b&gt; — tutto nella stessa cartella:&lt;br&gt;&lt;pre style=&apos;font-size:11px&apos;&gt;output/\n├── comunali.gpkg\n├── provinciali.gpkg\n└── edifici.gpkg&lt;/pre&gt;&lt;b&gt;✓ Attivata&lt;/b&gt; — stessa struttura dell'input:&lt;br&gt;&lt;pre style=&apos;font-size:11px&apos;&gt;output/\n├── strade/\n│   ├── comunali/comunali.gpkg\n│   └── provinciali/provinciali.gpkg\n└── edifici/edifici.gpkg&lt;/pre&gt;</source><translation>&lt;b&gt;Replicar estructura en disco&lt;/b&gt;&lt;br&gt;&lt;br&gt;Si tu carpeta de entrada tiene subcarpetas anidadas, esta opción decide cómo se organizan los GeoPackage de salida.&lt;br&gt;&lt;br&gt;&lt;b&gt;Ejemplo — tu carpeta:&lt;/b&gt;&lt;br&gt;&lt;pre style=&apos;font-size:11px&apos;&gt;proyecto/\n├── vias/\n│   ├── municipales/  →  calles.shp\n│   └── provinciales/  →  rutas.shp\n└── edificios/  →  residenciales.shp&lt;/pre&gt;&lt;b&gt;✗ Desactivada&lt;/b&gt; — todo en la misma carpeta:&lt;br&gt;&lt;pre style=&apos;font-size:11px&apos;&gt;output/\n├── municipales.gpkg\n├── provinciales.gpkg\n└── edificios.gpkg&lt;/pre&gt;&lt;b&gt;✓ Activada&lt;/b&gt; — misma estructura de la entrada:&lt;br&gt;&lt;pre style=&apos;font-size:11px&apos;&gt;output/\n├── vias/\n│   ├── municipales/municipales.gpkg\n│   └── provinciales/provinciales.gpkg\n└── edificios/edificios.gpkg&lt;/pre&gt;</translation></message>
    <message><source>&lt;b&gt;Cartella di input&lt;/b&gt;&lt;br&gt;La cartella che contiene i file vettoriali da convertire.&lt;br&gt;&lt;br&gt;Formati supportati: &lt;code&gt;.shp .tab .kml .kmz .gml .geojson .json .dxf .gpx .mif&lt;/code&gt;&lt;br&gt;Sono supportati anche file &lt;code&gt;.zip&lt;/code&gt; contenenti shapefile (letti tramite &lt;code&gt;/vsizip/&lt;/code&gt;, niente estrazione).</source><translation>&lt;b&gt;Carpeta de entrada&lt;/b&gt;&lt;br&gt;La carpeta que contiene los archivos vectoriales a convertir.&lt;br&gt;&lt;br&gt;Formatos compatibles: &lt;code&gt;.shp .tab .kml .kmz .gml .geojson .json .dxf .gpx .mif&lt;/code&gt;&lt;br&gt;También se soportan archivos &lt;code&gt;.zip&lt;/code&gt; que contengan shapefiles (leídos mediante &lt;code&gt;/vsizip/&lt;/code&gt;, sin extracción).</translation></message>
    <message><source>&lt;b&gt;Anteprima cartella&lt;/b&gt;&lt;br&gt;Risultato della scansione. Le colonne mostrano i metadati di ogni file. Eventuali problemi (CRS sconosciuto, encoding sospetto) compaiono nella colonna &lt;i&gt;Avvisi&lt;/i&gt;.</source><translation>&lt;b&gt;Vista previa de carpeta&lt;/b&gt;&lt;br&gt;Resultado del escaneo. Las columnas muestran los metadatos de cada archivo. Eventuales problemas (CRS desconocido, codificación sospechosa) aparecen en la columna &lt;i&gt;Avisos&lt;/i&gt;.</translation></message>
    <message><source>&lt;b&gt;Layer del progetto&lt;/b&gt;&lt;br&gt;Spunta i layer vettoriali da convertire. Dopo il nome trovi CRS e numero di feature; il &lt;i&gt;tooltip su ogni riga&lt;/i&gt; mostra il percorso del file sorgente.</source><translation>&lt;b&gt;Capas del proyecto&lt;/b&gt;&lt;br&gt;Marca las capas vectoriales a convertir. Después del nombre encontrarás CRS y número de features; el &lt;i&gt;tooltip en cada fila&lt;/i&gt; muestra la ruta del archivo fuente.</translation></message>
    <message><source>&lt;b&gt;Esegui&lt;/b&gt;&lt;br&gt;Avvia la conversione con le opzioni correnti.&lt;br&gt;&lt;br&gt;Si abilita solo quando sono stati scelti almeno un input (layer o scansione) e un percorso di output.</source><translation>&lt;b&gt;Ejecutar&lt;/b&gt;&lt;br&gt;Inicia la conversión con las opciones actuales.&lt;br&gt;&lt;br&gt;Se habilita solo cuando se han elegido al menos una entrada (capa o escaneo) y una ruta de salida.</translation></message>
    <message><source>&lt;b&gt;Apri cartella&lt;/b&gt;&lt;br&gt;Apre nel file manager di sistema la cartella che contiene i GeoPackage generati nell'ultima conversione.</source><translation>&lt;b&gt;Abrir carpeta&lt;/b&gt;&lt;br&gt;Abre en el explorador de archivos del sistema la carpeta que contiene los GeoPackage generados en la última conversión.</translation></message>
    <message><source>&lt;b&gt;Apri report&lt;/b&gt;&lt;br&gt;Riapre nel browser il report HTML dell'ultima conversione, con dettaglio di file convertiti, errori e avvisi.</source><translation>&lt;b&gt;Abrir reporte&lt;/b&gt;&lt;br&gt;Reabre en el navegador el reporte HTML de la última conversión, con detalle de archivos convertidos, errores y avisos.</translation></message>
</context>
</TS>
